# Telegram API данные
api_id: "YOUR_API_ID"         # Получить на my.telegram.org
api_hash: "YOUR_API_HASH"

# Фильтрация по обязательному тексту
require_text: false           # Должен ли быть обязательный текст в сообщении?
required_text: "ВАЖНО"       # Какой текст должен быть в сообщении?

# Копирование определённого фрагмента
copy_fragment: false          # Копировать только определённый фрагмент?
fragment_prefix: "ZM"        # С чего должен начинаться фрагмент (например, "ZM")
fragment_max_length: 20      # Максимальная длина фрагмента после префикса